name: image_cropper_gdx_plus_platform_interface
resolution: workspace
description: A common platform interface for the image_cropper_gdx_plus plugin.
version: 1.0.0
homepage: https://gurwinderdevx.com
repository: https://github.com/47gurvinder/flutter_image_cropper
issue_tracker: https://github.com/47gurvinder/flutter_image_cropper/issues
funding:
  - https://buymeacoffee.com/gurwinderdevx

environment:
  flutter: ">=3.28.0"
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
